# Generated by Django 4.2.28 on 2026-02-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_full_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_phone_number",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_birth_date",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_gender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_current_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_birth_place",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_religion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_education_level",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_occupation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_job_title",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="public_membership_date",
            field=models.BooleanField(default=False),
        ),
    ]
